package com.kvibe.app;

import android.Manifest; import android.app.*; import android.os.*; import android.content.*; import android.content.pm.PackageManager; import android.net.Uri; import android.provider.Settings; import android.view.*; import android.webkit.*; import androidx.activity.ComponentActivity; import androidx.core.app.ActivityCompat; import androidx.core.content.ContextCompat; import androidx.webkit.WebViewAssetLoader;

public class MainActivity extends ComponentActivity {
 private WebView web; private ValueCallback<Uri[]> chooser; private static final int PERMS=41, FILES=42;
 @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(0xff000000); web=new WebView(this); web.setBackgroundColor(0xff000000); WebSettings s=web.getSettings(); s.setJavaScriptEnabled(true); s.setDomStorageEnabled(true); s.setMediaPlaybackRequiresUserGesture(false); s.setAllowFileAccess(false); s.setAllowContentAccess(true); s.setSupportZoom(false); s.setBuiltInZoomControls(false); WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build(); web.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}}); web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest r){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=23 && (ContextCompat.checkSelfPermission(MainActivity.this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED || ContextCompat.checkSelfPermission(MainActivity.this,Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)){requestPermissions();} else r.grant(r.getResources());});} @Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){chooser=cb; Intent i=p.createIntent(); try{startActivityForResult(i,FILES);}catch(Exception e){chooser=null; return false;} return true;}}); setContentView(web); requestPermissions(); web.loadUrl("https://appassets.androidplatform.net/assets/index.html"); }
 private void requestPermissions(){if(Build.VERSION.SDK_INT>=23) ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},PERMS);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d); if(r==FILES&&chooser!=null){chooser.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(c,d)); chooser=null;}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);}
 @Override public void onBackPressed(){if(web.canGoBack()) web.goBack(); else super.onBackPressed();}
}
